# Generated by Django 6.0 on 2026-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
        ('treatment', '0003_treatmentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentChatMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Treatment Chat Message',
                'verbose_name_plural': 'Treatment Chat Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.chatmessage',),
        ),
        migrations.AlterField(
            model_name='treatmentbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
    ]
