# Generated by Django 6.0 on 2026-01-08 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostel_rooms/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('service_type', models.CharField(choices=[('pickup', 'Pick Up'), ('store_visit', 'Store Visit')], max_length=20)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('diet_type', models.CharField(choices=[('carnivore', 'Carnivore'), ('half_carnivore', 'Half Carnivore'), ('vegetarian', 'Vegetarian')], max_length=20)),
                ('pet_nature', models.CharField(max_length=100)),
                ('vaccination_status', models.CharField(max_length=100)),
                ('communicable_disease', models.BooleanField(default=False)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('police_report', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_treatments', models.ManyToManyField(blank=True, to='treatment.treatmenttype')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hostel.hostelroom')),
            ],
        ),
        migrations.CreateModel(
            name='HostelRoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hostel.hostelroom')),
            ],
        ),
    ]
